### ISSUE TITLE
IOS14 request

### ISSUE THREAD

**Issue by alian2plus** [Dcsyhi1998/CarMovie#1]
Kindly make one for IOS 14, pretty please!!

**Comment by Dcsyhi1998** [comment]
Am I correct in recognizing that this version is not compatible with iOS14?
If so, I think it would be difficult to support it. I currently do not have an iOS14 device, so I am unable to test it.

**Comment by alian2plus** [comment]
> Am I correct in recognizing that this version is not compatible with iOS14?
> 
> If so, I think it would be difficult to support it. I currently do not have an iOS14 device, so I am unable to test it.

I have downloaded it yesterday, the app opens with no crash, i insert couple videos put not yet test it with carplay. 

I'll give you the feedback when i do so.

**Comment by Dcsyhi1998** [comment]
We are waiting for your report.

**Comment by alian2plus** [comment]
> We are waiting for your report.

Sorry for being late, i have tested it and guess what? It just works great on v1.1 with zero issues.

You can confirm.
Iphone xs max IOS 14.4.2
