### ISSUE TITLE
Thank you for your development, feedback 14pm 16.3.1 It will crash when opening. Is this normal?

### ISSUE THREAD

**Issue by He-duoduo** [Dcsyhi1998/CarMovie#3]
Thank you for your development, feedback 14pm 16.3.1 It will crash when opening. Is this normal?

**Comment by Dcsyhi1998** [comment]
> Thank you for your development, feedback 14pm 16.3.1 It will crash when opening. Is this normal?

hello, how did you install it with trollstore?
When it crashes? on the iphone or with CarPlay?

**Comment by Dcsyhi1998** [comment]
how did you install it with trollstore?

**Comment by Dcsyhi1998** [comment]
> Open developer mode,download tipa file from here,and opened with TrollStore 2. 0.8 Can’t into app,just crashed !

Hmmm... It is difficult to identify the cause.
By the way, is AirWall working?

**Comment by Dcsyhi1998** [comment]
> Yes AirWall works normally CarMovie It shows normal on CarPlay, but it flashes back on the iPhone.

Just to confirm a couple of things, does the crash occur when you open CarMovie on the iPhone?
Or when you edit it?

Please uninstall "Presistence Helper" and install it again.

**Comment by Dcsyhi1998** [comment]
> Okay Helper has been uninstalled. After reinstalling CarMovie, the moment I opened CarMovie on my 14p, it flashed back without any operation.

this solution has been reported to me, try to test it.
[Twitter Link](https://x.com/kayhankaraman04/status/1738711926882926908)
