### ISSUE TITLE
On the iPhone app working correctly, but In CarPlay I can't see this app.

### ISSUE THREAD

**Issue by Kras-s-savchiK** [Dcsyhi1998/CarMovie#4]
On the iPhone app working correctly, but In CarPlay I can't see this app.
iOS 17.2 and 17.1

**Comment by Dcsyhi1998** [comment]
> On the iPhone app working correctly, but In CarPlay I can't see this app. iOS 17.2 and 17.1

hello, how did you install it with trollstore?

**Comment by Kras-s-savchiK** [comment]
im install it with Scarlet
Also it working in iOS 17.3 (just on device, not in CarPlay)

**Comment by Dcsyhi1998** [comment]
> im install it with Scarlet Also it working in iOS 17.3 (just on device, not in CarPlay)

CarMovie is now a TrollStore exclusive application. Therefore, we do not provide ipa files.

**Comment by Kras-s-savchiK** [comment]
O'K. But I can download from TrollStore and install with different app. And it's work! But Not in the car!
